
EXERCISE_LIBRARY = {

    # =========================================================================
    # CARDIO
    # =========================================================================

    "cardio": {

        "easy": [
            {
                "name": "Easy jogging",
                "type": "cardio",
                "environment": "outdoor",
                "duration_minutes": 15,
                "equipment_required": False,
            },
            {
                "name": "Low-impact knee lifts",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 12,
                "equipment_required": False,
            },
            {
                "name": "Easy outdoor walking",
                "type": "cardio",
                "environment": "outdoor",
                "duration_minutes": 20,
                "equipment_required": False,
            },
            {
                "name": "Brisk walking",
                "type": "cardio",
                "environment": "outdoor",
                "duration_minutes": 15,
                "equipment_required": False,
            },
            {
                "name": "Low-impact step jacks",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 15,
                "equipment_required": False,
            },
            {
                "name": "Marching in place",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 10,
                "equipment_required": False,
            },
            {
                "name": "Low-impact side steps",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 12,
                "equipment_required": False,
            },
            {
                "name": "Easy cycling",
                "type": "cardio",
                "environment": "outdoor",
                "duration_minutes": 15,
                "equipment_required": True,
            },
            {
                "name": "Light dancing",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 15,
                "equipment_required": False,
            },
            {
                "name": "Easy stair walking",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 10,
                "equipment_required": False,
            },
        ],

        "moderate": [
            {
                "name": "Tempo walking",
                "type": "cardio",
                "environment": "outdoor",
                "duration_minutes": 25,
                "equipment_required": False,
            },
            {
                "name": "Low-impact cardio circuit",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 20,
                "equipment_required": False,
            },
            {
                "name": "Stair intervals",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 20,
                "equipment_required": False,
            },
            {
                "name": "Walk-jog intervals",
                "type": "cardio",
                "environment": "outdoor",
                "duration_minutes": 25,
                "equipment_required": False,
            },
            {
                "name": "Step jacks",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 20,
                "equipment_required": False,
            },
            {
                "name": "Jogging",
                "type": "cardio",
                "environment": "outdoor",
                "duration_minutes": 25,
                "equipment_required": False,
            },
            {
                "name": "High-knee marching",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 15,
                "equipment_required": False,
            },
            {
                "name": "Cycling",
                "type": "cardio",
                "environment": "outdoor",
                "duration_minutes": 25,
                "equipment_required": True,
            },
            {
                "name": "Fast stair walking",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 15,
                "equipment_required": False,
            },
            {
                "name": "Dance cardio",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 25,
                "equipment_required": False,
            },
        ],

        "challenging": [
            {
                "name": "Sprint intervals",
                "type": "cardio",
                "environment": "outdoor",
                "duration_minutes": 25,
                "equipment_required": False,
            },
            {
                "name": "Jump rope",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 15,
                "equipment_required": True,
            },
            {
                "name": "Burpee intervals",
                "type": "cardio",
                "environment": "indoor",
                "sets": 4,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Jogging intervals",
                "type": "cardio",
                "environment": "outdoor",
                "duration_minutes": 30,
                "equipment_required": False,
            },
            {
                "name": "Jumping jacks",
                "type": "cardio",
                "environment": "indoor",
                "duration_minutes": 20,
                "equipment_required": False,
            },
            {
                "name": "Running intervals",
                "type": "cardio",
                "environment": "outdoor",
                "duration_minutes": 30,
                "equipment_required": False,
            },
            {
                "name": "Burpees",
                "type": "cardio",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "High knees",
                "type": "cardio",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Mountain climbers",
                "type": "cardio",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Fast cycling",
                "type": "cardio",
                "environment": "outdoor",
                "duration_minutes": 35,
                "equipment_required": True,
            },
        ],
    },


    # =========================================================================
    # UPPER BODY STRENGTH
    # =========================================================================

    "upper_body_strength": {

        "easy": [
            {
                "name": "Standing wall press",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Shoulder blade squeezes",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 12,
                "equipment_required": False,
            },
            {
                "name": "Wall plank",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Arm circles",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Scapular wall slides",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Seated shoulder raises",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Knee-supported plank",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Incline wall push-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Wall push-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Wall angels",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
        ],

        "moderate": [
            {
                "name": "Close-grip incline push-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Bear plank shoulder taps",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Resistance-band chest press",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": True,
            },
            
            {
                "name": "Incline push-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Shoulder taps",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Knee push-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Triceps dips",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Pike push-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Plank shoulder reaches",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Resistance-band rows",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": True,
            },
        ],

        "challenging": [
            {
                "name": "Archer push-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 6,
                "equipment_required": False,
            },
            {
                "name": "Decline diamond push-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 6,
                "equipment_required": False,
            },
            {
                "name": "Pseudo-planche push-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 6,
                "equipment_required": False,
            },
            
            {
                "name": "Standard push-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Decline push-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Diamond push-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Pike push-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Triceps dips",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 12,
                "equipment_required": False,
            },
            {
                "name": "Plank-to-push-up",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Resistance-band rows",
                "type": "strength",
                "environment": "indoor",
                "sets": 4,
                "reps": 12,
                "equipment_required": True,
            },
        ],
    },


    # =========================================================================
    # LOWER BODY STRENGTH
    # =========================================================================

    "lower_body_strength": {

        "easy": [

                        {
                "name": "Seated leg extensions",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Supported side leg raises",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Glute bridge pulses",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 12,
                "equipment_required": False,
            },
            {
                "name": "Chair squats",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Glute bridges",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 12,
                "equipment_required": False,
            },
            {
                "name": "Calf raises",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 12,
                "equipment_required": False,
            },
            {
                "name": "Standing leg raises",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Supported reverse lunges",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 6,
                "equipment_required": False,
            },
            {
                "name": "Wall sit",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Step-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 2,
                "reps": 8,
                "equipment_required": False,
            },
        ],

        "moderate": [
            {
                "name": "Sumo squats",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 12,
                "equipment_required": False,
            },
            {
                "name": "Lateral lunges",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Glute bridge march",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Bodyweight squats",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 12,
                "equipment_required": False,
            },
            {
                "name": "Reverse lunges",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Bulgarian split squats",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Single-leg glute bridges",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Step-ups",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Wall sit",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Calf raises",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 15,
                "equipment_required": False,
            },
        ],

        "challenging": [
            {
                "name": "Jumping lunges",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Pistol squat progression",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 6,
                "equipment_required": False,
            },
            {
                "name": "Single-leg hip thrusts",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Forward lunges",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Single-leg glute bridges",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Jump squats",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Bulgarian split squats",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Walking lunges",
                "type": "strength",
                "environment": "outdoor",
                "sets": 3,
                "reps": 12,
                "equipment_required": False,
            },
            {
                "name": "Single-leg squats to chair",
                "type": "strength",
                "environment": "indoor",
                "sets": 3,
                "reps": 6,
                "equipment_required": False,
            },
            {
                "name": "Wall sit",
                "type": "strength",
                "environment": "indoor",
                "sets": 4,
                "duration_seconds": 45,
                "equipment_required": False,
            },
        ],
    },


    # =========================================================================
    # CORE
    # =========================================================================

    "core": {

        "easy": [
            {
                "name": "Standing core knee lifts",
                "type": "core",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Bent-knee leg lifts",
                "type": "core",
                "environment": "indoor",
                "sets": 2,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Abdominal bracing",
                "type": "core",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Dead bug",
                "type": "core",
                "environment": "indoor",
                "sets": 2,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Bird-dog",
                "type": "core",
                "environment": "indoor",
                "sets": 2,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Glute bridge hold",
                "type": "core",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Knee plank",
                "type": "core",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Seated knee lifts",
                "type": "core",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Heel slides",
                "type": "core",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Pelvic tilts",
                "type": "core",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
        ],

        "moderate": [
            {
                "name": "Plank knee drives",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Flutter kicks",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Toe taps",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 12,
                "equipment_required": False,
            },
            {
                "name": "Forearm plank",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Heel taps",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 12,
                "equipment_required": False,
            },
            {
                "name": "Bicycle crunches",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 12,
                "equipment_required": False,
            },
            {
                "name": "Leg raises",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Dead bug",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Plank shoulder taps",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Reverse crunches",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
        ],

        "challenging": [
            {
                "name": "Dragon flag progression",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 6,
                "equipment_required": False,
            },
            {
                "name": "Hanging knee raises",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": True,
            },
            {
                "name": "Plank to pike",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Side plank",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Mountain climbers",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 20,
                "equipment_required": False,
            },
            {
                "name": "V-ups",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Plank jacks",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 15,
                "equipment_required": False,
            },
            {
                "name": "Hollow body hold",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Russian twists",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "reps": 16,
                "equipment_required": False,
            },
            {
                "name": "Long-lever plank",
                "type": "core",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 40,
                "equipment_required": False,
            },
        ],
    },


    # =========================================================================
    # FLEXIBILITY
    # =========================================================================

    "flexibility": {

        "easy": [
            {
                "name": "Wrist and forearm stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Standing calf stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Upper-back stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Cat-cow stretch",
                "type": "mobility",
                "environment": "indoor",
                "sets": 2,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Child's pose",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Neck side stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Shoulder stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Standing quad stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Seated hamstring stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Ankle mobility circles",
                "type": "mobility",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
        ],

        "moderate": [
            {
                "name": "World's greatest stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Lying spinal twist",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Kneeling quad stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Standing hamstring stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Hip-flexor stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Figure-four stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Butterfly stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Lunge hip-flexor stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Standing side bend",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Chest stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 30,
                "equipment_required": False,
            },
        ],

        "challenging": [
            {
                "name": "Lizard stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 40,
                "equipment_required": False,
            },
            {
                "name": "Half split stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Low lunge with rotation",
                "type": "mobility",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Seated spinal twist",
                "type": "mobility",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Chest doorway stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Pigeon pose",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Deep lunge stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Extended child's pose",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 40,
                "equipment_required": False,
            },
            {
                "name": "Seated forward fold",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 40,
                "equipment_required": False,
            },
            {
                "name": "Cobra stretch",
                "type": "flexibility",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 30,
                "equipment_required": False,
            },
        ],
    },


    # =========================================================================
    # BALANCE
    # =========================================================================

    "balance": {

        "easy": [
            {
                "name": "Supported side leg balance",
                "type": "balance",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Marching balance",
                "type": "balance",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Heel raises with balance",
                "type": "balance",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Tandem stance",
                "type": "balance",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Heel-to-toe walk",
                "type": "balance",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 30,
                "equipment_required": False,
            },
            {
                "name": "Supported single-leg stand",
                "type": "balance",
                "environment": "indoor",
                "sets": 2,
                "duration_seconds": 15,
                "equipment_required": False,
            },
            {
                "name": "Weight shifts",
                "type": "balance",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Side-to-side steps",
                "type": "balance",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Toe-to-heel rocking",
                "type": "balance",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Supported heel raises",
                "type": "balance",
                "environment": "indoor",
                "sets": 2,
                "reps": 10,
                "equipment_required": False,
            },
        ],

        "moderate": [
            {
                "name": "Single-leg clock taps",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 6,
                "equipment_required": False,
            },
            {
                "name": "Tandem squat",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Single-leg toe taps",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Single-leg stand",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 20,
                "equipment_required": False,
            },
            {
                "name": "Single-leg reach",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 6,
                "equipment_required": False,
            },
            {
                "name": "Heel-to-toe walk",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "duration_seconds": 40,
                "equipment_required": False,
            },
            {
                "name": "Single-leg calf raise",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Lateral leg swings",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
            {
                "name": "Clock reach",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 6,
                "equipment_required": False,
            },
            {
                "name": "Single-leg knee lift",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
        ],

        "challenging": [
            {
                "name": "Single-leg squat",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 6,
                "equipment_required": False,
            },
            {
                "name": "Lateral bound and hold",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Single-leg reach matrix",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Single-leg stand with reach",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Single-leg balance with knee drive",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Single-leg Romanian deadlift",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Lateral hop and hold",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Single-leg squat reach",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 6,
                "equipment_required": False,
            },
            {
                "name": "Single-leg hop",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 8,
                "equipment_required": False,
            },
            {
                "name": "Skater balance",
                "type": "balance",
                "environment": "indoor",
                "sets": 3,
                "reps": 10,
                "equipment_required": False,
            },
        ],
    },
}


# ============================================================================
# EXERCISE RETRIEVAL FUNCTIONS
# ============================================================================

def get_exercises(
    focus,
    difficulty,
    outdoor_exercise_accepted=True,
):
    """
    Return exercises matching the weekly focus and difficulty.

    If outdoor exercise is not accepted, outdoor exercises are excluded.
    Indoor exercises remain available as alternatives.
    """

    if focus not in EXERCISE_LIBRARY:
        raise ValueError(
            f"Unknown focus: {focus}"
        )

    if difficulty not in EXERCISE_LIBRARY[focus]:
        raise ValueError(
            f"Unknown difficulty: {difficulty}"
        )

    exercises = EXERCISE_LIBRARY[focus][difficulty]

    if outdoor_exercise_accepted:
        return exercises.copy()

    return [
        exercise
        for exercise in exercises
        if exercise["environment"] != "outdoor"
    ]


def select_exercise(
    focus,
    difficulty,
    outdoor_exercise_accepted=True,
    index=0,
    offset=0,
):
    exercises = get_exercises(
        focus,
        difficulty,
        outdoor_exercise_accepted,
    )

    if not exercises:
        return None

    index = (index + offset) % len(exercises)

    return exercises[index]